# Generated by YCM Generator at 2020-03-22 20:36:41.941511

# This file is NOT licensed under the GPLv3, which is the license for the rest
# of YouCompleteMe.
#
# Here's the license text for this file:
#
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org/>

import os
import ycm_core

flags = [
    '-x',
    'c++',
    '-DDAGTASKS_EXPORTS',
    '-DDAGTASKS_SHARED',
    '-DGTEST_CREATE_SHARED_LIBRARY=1',
    '-DGTEST_HAS_PTHREAD=1',
    '-Ddagtasks_EXPORTS',
    '-Dgmock_EXPORTS',
    '-Dgmock_main_EXPORTS',
    '-Dgtest_EXPORTS',
    '-Dgtest_main_EXPORTS',
    '-I/Users/matthew.hoggan/Devel/github/mehoggan/dag_scheduler/lib/..',
    '-I/Users/matthew.hoggan/Devel/github/mehoggan/dag_scheduler/lib/../include',
    '-I/Users/matthew.hoggan/Devel/github/mehoggan/dag_scheduler/tests/..',
    '-I/Users/matthew.hoggan/Devel/github/mehoggan/dag_scheduler/tests/../include',
    '-I/Users/matthew.hoggan/Devel/github/mehoggan/dag_scheduler/tests/./utils',
    '-I/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-codeartifact/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-cognito-identity/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-cognito-sync/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-ssm-incidents/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-wisdom/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-cloud9/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-fsx/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-sqs/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-identity-management/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-iot/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-globalaccelerator/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-redshift-data/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-ecs/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-marketplace-catalog/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-budgets/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-cloudtrail/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-resource-groups/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-lex-models/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-application-insights/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-mediapackage-vod/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-kinesis-video-archived-media/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-wellarchitected/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-transcribestreaming/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-appsync/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-worklink/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-servicecatalog/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-firehose/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-secretsmanager/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-cloudsearch/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-iotevents-data/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-mediastore/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-identitystore/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-codestar/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-chime-sdk-meetings/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-docdb/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-personalize-events/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-ecr/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-honeycode/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-rum/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-email/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-lightsail/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-appflow/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-elasticloadbalancingv2/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-lambda/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-alexaforbusiness/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-amplify/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-datapipeline/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-discovery/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-qldb-session/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-apigatewaymanagementapi/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-cloudhsmv2/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-codedeploy/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-queues/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-license-manager/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-access-management/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-backup-gateway/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-dataexchange/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-qldb/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-polly/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-mobile/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-s3control/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-mobileanalytics/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-personalize-runtime/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-rbin/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-fms/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-states/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-support/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-directconnect/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-AWSMigrationHub/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-networkmanager/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-rds-data/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-mturk-requester/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-events/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-dynamodbstreams/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-pricing/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-opsworkscm/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-sagemaker-runtime/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-nimble/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-servicediscovery/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-kinesisanalyticsv2/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-glue/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-sms/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-opsworks/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-mwaa/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-textract/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-serverlessrepo/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-resourcegroupstaggingapi/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-cloudcontrol/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-kendra/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-inspector/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-snowball/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-compute-optimizer/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-lex/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-translate/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-iotsecuretunneling/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-backup/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-sms-voice/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-personalize/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-accessanalyzer/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-applicationcostprofiler/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-fis/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-migration-hub-refactor-spaces/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-apigatewayv2/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-appconfigdata/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-s3/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-iotthingsgraph/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-sns/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-finspace-data/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-greengrass/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-gamelift/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-monitoring/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-iot1click-devices/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-route53/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-cognito-idp/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-sso-oidc/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-timestream-query/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-auditmanager/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-medialive/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-redshift/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-managedblockchain/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-codecommit/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-kinesisanalytics/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/testing-resources/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-transcribe/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-codestar-connections/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-meteringmarketplace/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-panorama/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-kms/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-marketplace-entitlement/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-kafkaconnect/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-iotwireless/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-devicefarm/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-forecastquery/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-athena/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-finspace/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-savingsplans/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-chime-sdk-messaging/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-text-to-speech/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-comprehend/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-route53domains/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-lexv2-runtime/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-kafka/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-ssm/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-batch/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-ds/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-iotfleethub/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-account/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-storagegateway/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-service-quotas/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-codebuild/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-route53-recovery-control-config/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-migrationhub-config/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-network-firewall/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-connect/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-iot-data/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-core/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-apigateway/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-amplifyuibuilder/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-migrationhubstrategy/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-databrew/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-eventbridge/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-iot-jobs-data/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-codeguru-reviewer/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-healthlake/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-sts/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-snow-device-management/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-es/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-sagemaker-a2i-runtime/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-acm/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-comprehendmedical/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-timestream-write/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-ec2/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-sagemaker-edge/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-ec2-instance-connect/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-organizations/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-apprunner/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-sagemaker/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-ram/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-lakeformation/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-rekognition/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-frauddetector/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-location/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-appstream/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-ce/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-kinesis-video-media/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-customer-profiles/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-sso-admin/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-acm-pca/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-appintegrations/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-connectparticipant/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-imagebuilder/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-wafv2/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-shield/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-awstransfer/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-signer/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-rds/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-quicksight/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-swf/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-s3-encryption/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-kinesis/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-robomaker/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-iot1click-projects/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-xray/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-config/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-workmailmessageflow/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-elasticbeanstalk/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-elasticloadbalancing/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-iotsitewise/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-application-autoscaling/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-waf-regional/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-proton/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-marketplacecommerceanalytics/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-codepipeline/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-elasticache/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-amplifybackend/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-s3-crt/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-dynamodb/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-securityhub/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-groundstation/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-dax/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-cloudsearchdomain/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-pinpoint-email/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-dms/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-guardduty/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-ecr-public/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-elasticmapreduce/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-inspector2/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-autoscaling/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-importexport/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-servicecatalog-appregistry/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-autoscaling-plans/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-route53-recovery-readiness/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-transfer/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-ivs/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-cur/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-elastic-inference/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-pi/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-logs/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-iotevents/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-workspaces-web/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-opensearch/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-iottwinmaker/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-sagemaker-featurestore-runtime/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-health/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-elastictranscoder/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-mediaconnect/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-cloudfront/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-cloudformation/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-voice-id/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-neptune/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-detective/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-synthetics/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/crt/aws-crt-cpp/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/crt/aws-crt-cpp/crt/aws-c-compression/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/crt/aws-crt-cpp/crt/aws-c-http/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/crt/aws-crt-cpp/crt/aws-c-mqtt/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/crt/aws-crt-cpp/crt/aws-c-event-stream/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/crt/aws-crt-cpp/crt/aws-c-common/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/crt/aws-crt-cpp/crt/aws-c-common/verification/cbmc/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/crt/aws-crt-cpp/crt/aws-c-common/verification/cbmc/templates/template-for-repository/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/crt/aws-crt-cpp/crt/aws-lc/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/crt/aws-crt-cpp/crt/aws-lc/third_party/googletest/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/crt/aws-crt-cpp/crt/s2n/tests/cbmc/aws-verification-model-for-libcrypto/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/crt/aws-crt-cpp/crt/s2n/tests/cbmc/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/crt/aws-crt-cpp/crt/s2n/tests/cbmc/templates/template-for-repository/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/crt/aws-crt-cpp/crt/s2n/tests/sidetrail/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/crt/aws-crt-cpp/crt/aws-c-io/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/crt/aws-crt-cpp/crt/aws-checksums/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/crt/aws-crt-cpp/crt/aws-c-cal/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/crt/aws-crt-cpp/crt/aws-c-auth/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/crt/aws-crt-cpp/crt/aws-c-s3/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-sesv2/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-grafana/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-kinesisvideo/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-workmail/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-waf/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-ssm-contacts/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-dlm/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-elasticfilesystem/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-devops-guru/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-route53-recovery-cluster/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-chime/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-appmesh/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-codestar-notifications/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-schemas/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-clouddirectory/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-pinpoint/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-forecast/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-sdb/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-mediastore-data/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-macie/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-mediatailor/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-mediaconvert/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-lookoutequipment/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-memorydb/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-s3outposts/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-eks/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-chime-sdk-identity/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-lookoutmetrics/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-cloudhsm/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-amp/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-drs/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-mgn/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-resiliencehub/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-iam/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-emr-containers/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-mediapackage/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-sso/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-glacier/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-connect-contact-lens/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-evidently/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-mq/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-codeguruprofiler/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-datasync/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-braket/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-lookoutvision/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-iotdeviceadvisor/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-workspaces/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-machinelearning/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-ebs/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-route53resolver/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-greengrassv2/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-appconfig/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-kinesis-video-signaling/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-lexv2-models/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-iotanalytics/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-outposts/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-macie2/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/aws-sdk-cpp-src/aws-cpp-sdk-workdocs/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/boostbeast/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/googletest-src/googlemock',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/googletest-src/googlemock/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/googletest-src/googletest',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/googletest-src/googletest/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/rapidjson-src/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/yaml-cpp-src/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/yaml-cpp-build/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/cpprestsdk-src/Release/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/libpqxx-src/include',
    '-I/Users/matthew.hoggan/Devel/build/github/mehoggan/dag_scheduler/rapidjson-src/include',
    '-I/usr/local/opt/openssl@3/include',
    '-W',
    '-Wall',
    '-Wcast-align',
    '-Wcast-qual',
    '-Wchar-subscripts',
    '-Wconversion',
    '-Werror',
    '-Winline',
    '-Wno-unknown-warning-option',
    '-Wpointer-arith',
    '-Wredundant-decls',
    '-Wreturn-type',
    '-Wshadow',
    '-Wswitch',
    '-Wunused-parameter',
    '-Wwrite-strings',
    '-std=c++11',
    '-isystem', '/tmp/tmpv89dqm/googletest-src/googlemock',
    '-isystem', '/tmp/tmpv89dqm/googletest-src/googlemock/include',
    '-isystem', '/tmp/tmpv89dqm/googletest-src/googletest',
    '-isystem', '/tmp/tmpv89dqm/googletest-src/googletest/include',
    '-install_name',
    '-std=c++11',
    '-std=gnu++11',
    '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk',
    '-isystem', '/private/var/folders/9n/xdn5ntps2qqfh_0tm7b9p74h0000gp/T/tmpLezTYz/googletest-src/googlemock',
    '-isystem', '/private/var/folders/9n/xdn5ntps2qqfh_0tm7b9p74h0000gp/T/tmpLezTYz/googletest-src/googlemock/include',
    '-isystem', '/private/var/folders/9n/xdn5ntps2qqfh_0tm7b9p74h0000gp/T/tmpLezTYz/googletest-src/googletest',
    '-isystem', '/private/var/folders/9n/xdn5ntps2qqfh_0tm7b9p74h0000gp/T/tmpLezTYz/googletest-src/googletest/include',
]


# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# You can get CMake to generate this file for you by adding:
#   set( CMAKE_EXPORT_COMPILE_COMMANDS 1 )
# to your CMakeLists.txt file.
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags. Notice that YCM itself uses that approach.
compilation_database_folder = ''

if os.path.exists( compilation_database_folder ):
  database = ycm_core.CompilationDatabase( compilation_database_folder )
else:
  database = None

SOURCE_EXTENSIONS = [ '.C', '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]

def DirectoryOfThisScript():
  return os.path.dirname( os.path.abspath( __file__ ) )


def MakeRelativePathsInFlagsAbsolute( flags, working_directory ):
  if not working_directory:
    return list( flags )
  new_flags = []
  make_next_absolute = False
  path_flags = [ '-isystem', '-I', '-iquote', '--sysroot=' ]
  for flag in flags:
    new_flag = flag

    if make_next_absolute:
      make_next_absolute = False
      if not flag.startswith( '/' ):
        new_flag = os.path.join( working_directory, flag )

    for path_flag in path_flags:
      if flag == path_flag:
        make_next_absolute = True
        break

      if flag.startswith( path_flag ):
        path = flag[ len( path_flag ): ]
        new_flag = path_flag + os.path.join( working_directory, path )
        break

    if new_flag:
      new_flags.append( new_flag )
  return new_flags


def IsHeaderFile( filename ):
  extension = os.path.splitext( filename )[ 1 ]
  return extension in [ '.H', '.h', '.hxx', '.hpp', '.hh' ]


def GetCompilationInfoForFile( filename ):
  # The compilation_commands.json file generated by CMake does not have entries
  # for header files. So we do our best by asking the db for flags for a
  # corresponding source file, if any. If one exists, the flags for that file
  # should be good enough.
  if IsHeaderFile( filename ):
    basename = os.path.splitext( filename )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if os.path.exists( replacement_file ):
        compilation_info = database.GetCompilationInfoForFile(
          replacement_file )
        if compilation_info.compiler_flags_:
          return compilation_info
    return None
  return database.GetCompilationInfoForFile( filename )


def FlagsForFile( filename, **kwargs ):
  if database:
    # Bear in mind that compilation_info.compiler_flags_ does NOT return a
    # python list, but a "list-like" StringVec object
    compilation_info = GetCompilationInfoForFile( filename )
    if not compilation_info:
      return None

    final_flags = MakeRelativePathsInFlagsAbsolute(
      compilation_info.compiler_flags_,
      compilation_info.compiler_working_dir_ )

  else:
    relative_to = DirectoryOfThisScript()
    final_flags = MakeRelativePathsInFlagsAbsolute( flags, relative_to )

  return {
    'flags': final_flags,
    'do_cache': True
  }

def Settings( **kwargs ):
    language = kwargs[ 'language' ]
    if language == 'cfamily':
        return {
            'flags': flags
        }

    return {}
